baseURL: "https://moniquelive.com"
languageCode: pt-br
DefaultContentLanguage: pt-br

title: Monique Oliveira
theme: dream
ignoreErrors:
  - error-remote-getjson
  - error-missing-instagram-accesstoken

googleAnalytics: UA-129884631-1
DisqusShortname: moniquelive-com
enableRobotsTXT: true

copyright: '<div style="display:flex;align-items:center"><a rel="license" style="margin-right:.8rem" href="http://creativecommons.org/licenses/by-nc-sa/4.0/"><img alt="licença" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png" /></a><span>Copyright &copy; 2018-2021 Monique Oliveira some rights reserved</span></div>'

SectionPagesMenu: main
Paginate: 9
enableEmoji: true

markup:
  goldmark:
    renderer:
      unsafe: true

sitemap:
  changefreq: monthly
  priority: 0.5
  filename: sitemap.xml

params:
  title: Monique Oliveira
  favicon: favicons/favicon.ico
  description: Uma ser humana em busca de si mesma.
  author: moniquelive
  avatar: /images/me.jpg
  motto: Uma ser humana em busca de si mesma.

  # youtube: "https://www.youtube.com/channel/UCML4uqYh36vkI0UTTGBxByg"
  facebook: cyberleo
  twitter: moniquelive
  instagram: monique.live
  github: lccro
  linkedin: moniquelive
  stackoverflow: 9793/cyber-oliveira
  siteStartYear: 2018

  # dark mode
  darkLinkColor: "#f77"
  darkNav: true
  dark404Button: true

  background: "#333"
  # backgroundImage: /images/background.jpg

  enableSearch: true

taxonomies:
  category: categories
  series: series
  tag: tags

outputs:
  home: [ HTML, RSS, JSON ]

